en:
  greeting: "Welcome to the Calculator! Enter your name:"
  hello: "Hi #{name}"
  name_error: "Make sure to use a valid name"
  number_error: "Hmm, that doesn't appear to be a valid number"
  first_number: "What's the first number?"
  second_number: "What's the second number?"
  operator_error: "Must choose 1, 2, 3 or 4"
  subsequent_request: "Do you want to perform another calculation? (Y to calculate again)"
  parting_words: "Thank you for using the calculator!"
es:
  greeting: "Bienvenido a la calculadora, introduzca tu nombre!"
  hello: "Hola #{name}"
  name_error: "Por favor, utilice un nombre valido"
  number_error: "Parece que no es numero correcto"
  first_number: "Cual es el primer numero?"
  second_number: "Cual es el segundo numero?"
  operator_error: "Hay que utilizar entre 1, 2, 3 o 4"
  subsequent_request: "Quieres hacer otra calculacion? (Y para hacerlo de nuevo)"
  parting_words: "Gracias por usar la calculadora"